// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIfuvMXIxW9ZnDV-NBinwdCwEfi9ST78',
    appId: '1:585727981044:android:94f1d5a2e8873ae7f1b5a1',
    messagingSenderId: '585727981044',
    projectId: 'flufire-instagram-v2',
    storageBucket: 'flufire-instagram-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJ46ctUpzcQkwI7_SFVN9D2cwLu543e4',
    appId: '1:585727981044:ios:4ee91d116764587cf1b5a1',
    messagingSenderId: '585727981044',
    projectId: 'flufire-instagram-v2',
    storageBucket: 'flufire-instagram-v2.appspot.com',
    iosClientId: '585727981044-v6r6gmcuhcsohpp9t3rto5bkpucpqu2c.apps.googleusercontent.com',
    iosBundleId: 'com.clone.instargram.instagramV2',
  );
}
